server:
  port: ${PORT}

spring:
  config:
    import: file:src/main/resources/.env[.properties]
  application:
    name: c106
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
  data:
    mongodb:
      host: ${MONGODB_HOST}
      port: ${MONGODB_PORT}
      database: ${MONGODB_DB}
      username: ${MONGODB_USERNAME}
      password: ${MONGODB_PASSWORD}
      authentication-database: admin
    jpa:
      repositories:
        bootstrap-mode: deferred
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

jwt:
  secret: ${JWT_SECRET_KEY}
  access:
    expiration: ${JWT_ACCESS_EXPIRATION}
    header: Authorization
  refresh:
    expiration: ${JWT_REFRESH_EXPIRATION}
    header: Authorization-refresh

logging:
  level:
    root: ${LOG_LEVEL:INFO}
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG
      hibernate:
        type:
          descriptor:
            sql: trace
    io:
      awspring:
        cloud: debug
  pattern:
    dateformat: yyyy-MM-dd'T'HH:mm:ss.SSSZ,Asia/Seoul

springdoc:
  swagger-ui:
    groups-order: DESC
    tags-sorter: alpha
    operations-sorter: method
    disable-swagger-default-url: true
    display-request-duration: true
    default-models-expand-depth: 2
    default-model-expand-depth: 2
  api-docs:
    path: /api-docs
    show-actuator: true
    default-consumes-media-type: application/json
    default-produces-media-type: application/json
    writer-with-default-pretty-printer: true
    model-and-view-allowed: true
    paths-to-match: /api/v1/**
